// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'instantly2-mcp/filtering';
import { Metadata, asTextContentResult } from 'instantly2-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Instantly2 from 'instantly2';

export const metadata: Metadata = {
  resource: 'v2',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/api/v2/api-keys',
  operationId: 'createAPIKey',
};

export const tool: Tool = {
  name: 'create_api_key_v2',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nRequires one of the following scopes: `api_keys:create`, `api_keys:all`, `all:create`, `all:all`\n\n# Response Schema\n```json\n{\n  $ref: '#/$defs/api_key',\n  $defs: {\n    api_key: {\n      type: 'object',\n      title: 'API Key',\n      description: 'API Key',\n      properties: {\n        id: {\n          type: 'string'\n        },\n        key: {\n          type: 'string'\n        },\n        name: {\n          type: 'string'\n        },\n        organization_id: {\n          type: 'string'\n        },\n        scopes: {\n          type: 'array',\n          items: {\n            type: 'string',\n            enum: [              'all:all',\n              'all:create',\n              'all:read',\n              'all:update',\n              'all:delete',\n              'ai_agents:all',\n              'ai_agents:create',\n              'ai_agents:read',\n              'ai_agents:update',\n              'ai_agents:delete',\n              'api_keys:all',\n              'api_keys:create',\n              'api_keys:read',\n              'api_keys:update',\n              'api_keys:delete',\n              'audit_logs:all',\n              'audit_logs:create',\n              'audit_logs:read',\n              'audit_logs:update',\n              'audit_logs:delete',\n              'account_campaign_mappings:all',\n              'account_campaign_mappings:create',\n              'account_campaign_mappings:read',\n              'account_campaign_mappings:update',\n              'account_campaign_mappings:delete',\n              'campaigns:all',\n              'campaigns:create',\n              'campaigns:read',\n              'campaigns:update',\n              'campaigns:delete',\n              'inbox_placement_tests:all',\n              'inbox_placement_tests:create',\n              'inbox_placement_tests:read',\n              'inbox_placement_tests:update',\n              'inbox_placement_tests:delete',\n              'inbox_placement_analytics:all',\n              'inbox_placement_analytics:create',\n              'inbox_placement_analytics:read',\n              'inbox_placement_analytics:update',\n              'inbox_placement_analytics:delete',\n              'inbox_placement_reports:all',\n              'inbox_placement_reports:create',\n              'inbox_placement_reports:read',\n              'inbox_placement_reports:update',\n              'inbox_placement_reports:delete',\n              'lead_lists:all',\n              'lead_lists:create',\n              'lead_lists:read',\n              'lead_lists:update',\n              'lead_lists:delete',\n              'leads:all',\n              'leads:create',\n              'leads:read',\n              'leads:update',\n              'leads:delete',\n              'background-jobs:all',\n              'background-jobs:create',\n              'background-jobs:read',\n              'background-jobs:update',\n              'background-jobs:delete',\n              'custom_tags:all',\n              'custom_tags:create',\n              'custom_tags:read',\n              'custom_tags:update',\n              'custom_tags:delete',\n              'accounts:all',\n              'accounts:create',\n              'accounts:read',\n              'accounts:update',\n              'accounts:delete',\n              'block_list_entries:all',\n              'block_list_entries:create',\n              'block_list_entries:read',\n              'block_list_entries:update',\n              'block_list_entries:delete',\n              'lead-labels:all',\n              'lead-labels:create',\n              'lead-labels:read',\n              'lead-labels:update',\n              'lead-labels:delete',\n              'email_verifications:all',\n              'email_verifications:create',\n              'email_verifications:read',\n              'emails:all',\n              'emails:create',\n              'emails:read',\n              'emails:update',\n              'emails:delete',\n              'workspaces:all',\n              'workspaces:create',\n              'workspaces:read',\n              'workspaces:update',\n              'workspaces:delete',\n              'workspace_group_members:all',\n              'workspace_group_members:create',\n              'workspace_group_members:read',\n              'workspace_group_members:update',\n              'workspace_group_members:delete',\n              'workspace_members:all',\n              'workspace_members:create',\n              'workspace_members:read',\n              'workspace_members:update',\n              'workspace_members:delete',\n              'subsequences:all',\n              'subsequences:create',\n              'subsequences:read',\n              'subsequences:update',\n              'subsequences:delete',\n              'security_tokens:all',\n              'security_tokens:create',\n              'security_tokens:read',\n              'security_tokens:update',\n              'security_tokens:delete'\n            ]\n          }\n        },\n        timestamp_created: {\n          type: 'string',\n          format: 'date-time'\n        },\n        timestamp_updated: {\n          type: 'string',\n          format: 'date-time'\n        }\n      },\n      required: [        'id',\n        'key',\n        'name',\n        'organization_id',\n        'scopes',\n        'timestamp_created',\n        'timestamp_updated'\n      ]\n    }\n  }\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
      },
      scopes: {
        type: 'array',
        items: {
          type: 'string',
          enum: [
            'all:all',
            'all:create',
            'all:read',
            'all:update',
            'all:delete',
            'ai_agents:all',
            'ai_agents:create',
            'ai_agents:read',
            'ai_agents:update',
            'ai_agents:delete',
            'api_keys:all',
            'api_keys:create',
            'api_keys:read',
            'api_keys:update',
            'api_keys:delete',
            'audit_logs:all',
            'audit_logs:create',
            'audit_logs:read',
            'audit_logs:update',
            'audit_logs:delete',
            'account_campaign_mappings:all',
            'account_campaign_mappings:create',
            'account_campaign_mappings:read',
            'account_campaign_mappings:update',
            'account_campaign_mappings:delete',
            'campaigns:all',
            'campaigns:create',
            'campaigns:read',
            'campaigns:update',
            'campaigns:delete',
            'inbox_placement_tests:all',
            'inbox_placement_tests:create',
            'inbox_placement_tests:read',
            'inbox_placement_tests:update',
            'inbox_placement_tests:delete',
            'inbox_placement_analytics:all',
            'inbox_placement_analytics:create',
            'inbox_placement_analytics:read',
            'inbox_placement_analytics:update',
            'inbox_placement_analytics:delete',
            'inbox_placement_reports:all',
            'inbox_placement_reports:create',
            'inbox_placement_reports:read',
            'inbox_placement_reports:update',
            'inbox_placement_reports:delete',
            'lead_lists:all',
            'lead_lists:create',
            'lead_lists:read',
            'lead_lists:update',
            'lead_lists:delete',
            'leads:all',
            'leads:create',
            'leads:read',
            'leads:update',
            'leads:delete',
            'background-jobs:all',
            'background-jobs:create',
            'background-jobs:read',
            'background-jobs:update',
            'background-jobs:delete',
            'custom_tags:all',
            'custom_tags:create',
            'custom_tags:read',
            'custom_tags:update',
            'custom_tags:delete',
            'accounts:all',
            'accounts:create',
            'accounts:read',
            'accounts:update',
            'accounts:delete',
            'block_list_entries:all',
            'block_list_entries:create',
            'block_list_entries:read',
            'block_list_entries:update',
            'block_list_entries:delete',
            'lead-labels:all',
            'lead-labels:create',
            'lead-labels:read',
            'lead-labels:update',
            'lead-labels:delete',
            'email_verifications:all',
            'email_verifications:create',
            'email_verifications:read',
            'emails:all',
            'emails:create',
            'emails:read',
            'emails:update',
            'emails:delete',
            'workspaces:all',
            'workspaces:create',
            'workspaces:read',
            'workspaces:update',
            'workspaces:delete',
            'workspace_group_members:all',
            'workspace_group_members:create',
            'workspace_group_members:read',
            'workspace_group_members:update',
            'workspace_group_members:delete',
            'workspace_members:all',
            'workspace_members:create',
            'workspace_members:read',
            'workspace_members:update',
            'workspace_members:delete',
            'subsequences:all',
            'subsequences:create',
            'subsequences:read',
            'subsequences:update',
            'subsequences:delete',
            'security_tokens:all',
            'security_tokens:create',
            'security_tokens:read',
            'security_tokens:update',
            'security_tokens:delete',
          ],
        },
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: ['name', 'scopes'],
  },
  annotations: {},
};

export const handler = async (client: Instantly2, args: Record<string, unknown> | undefined) => {
  const { jq_filter, ...body } = args as any;
  return asTextContentResult(await maybeFilter(jq_filter, await client.v2.createAPIKey(body)));
};

export default { metadata, tool, handler };
